"""payment and installment models

Revision ID: 496a334f5b34
Revises: 248e3705cd04
Create Date: 2026-08-09 09:28:16.055559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496a334f5b34'
down_revision: Union[str, Sequence[str], None] = '248e3705cd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('total_terms', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'SKIPPED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('term_number', sa.Integer(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'term_number', name='uq_subscription_term')
    )
    op.add_column('subscriptions', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('billing_day', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('subscriptions', sa.Column('interval', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='subscriptioninterval', native_enum=False), nullable=False))
    op.add_column('subscriptions', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', 'COMPLETED', name='subscriptionstatus', native_enum=False), nullable=False))
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'interval')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'billing_day')
    op.drop_column('subscriptions', 'amount')
    op.drop_column('subscriptions', 'notes')
    op.drop_table('payments')
    op.drop_table('installments')
    # ### end Alembic commands ###
